export const TASK_MANAGEMENT = 'TASK_MANAGEMENT';
export const LOGIN_MANAGEMENT = 'LOGIN_MANAGEMENT';
export const SIGNUP_MANAGEMENT = 'SIGNUP_MANAGEMENT';
export const RESET_PASSWORD_MANAGEMENT = 'RESET_PASSWORD_MANAGEMENT';
export const RESET_NEW_PASSWORD_MANAGEMENT = 'RESET_NEW_PASSWORD_MANAGEMENT';
