export const SHOW_LOADING = 'GLOBAL_SHOW_LOADING';
export const HIDE_LOADING = 'GLOBAL_HIDE_LOADING';

export const SHOW_SIDEBAR = 'GLOBAL_SHOW_SIDEBAR';
export const HIDE_SIDEBAR = 'GLOBAL_HIDE_SIDEBAR';
